config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "questions#index"
  resources :questions do
    resources :answers, only: [:create, :show]
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :description,
    presence: true,
    length: {minimum: 50}

  validates :user_id,
    presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, -> { order(created_at: :desc) }
  belongs_to :user

  validates :title,
    presence: true,
    length: {minimum: 40, maximum: 255}

  validates :description,
    presence: true,
    length: {minimum: 150}

    validates :user_id,
      presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :users
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:github]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.name   # assuming the user model has a name
      user.last_name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      user.save
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to question_path(@question)
    else
      flash[:warning] = @answer.errors.full_messages.join(".  ")
      redirect_to question_path(@question)
    end

  end

  private

  def answer_params
    params.require(:answer).permit(:description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_question_author, only: [:destroy, :edit]
  def index
    @questions = Question.order(created_at: :desc)
  end

  def new
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      flash[:info] = "Question created."
      redirect_to @question
    else
      flash[:warning] = @question.errors.full_messages.join(".  ")
      render :action => 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      flash[:info] = "Question Updated."
      redirect_to @question
    else
      flash[:warning] = @question.errors.full_messages.join(".  ")
      render 'edit'
    end
  end

  def destroy
    Question.destroy(params[:id])
    flash[:info] = "Question Deleted."
    redirect_to :action => "index"
  end

  private
    # Is there a better way to do this?
    def question_params
      question_hash = params.require(:question).permit(:title, :description)
      question_hash[:user_id] = current_user.id
      question_hash
    end

    def authenticate_question_author
      @question = Question.find(params[:id])
      unless current_user == @question.user_id
        flash[:error] = "You must be the owner of the question to do that."
        redirect_to question_path(@question)
      end

    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer_form.html.erb
<%= form_for([@question, @question.answers.create]) do |f| %>

  <%= f.label :description, "Add an Answer:" %>
  <%= f.text_area :description %>
  <%= f.submit :class => "button" %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.keys.each do |type| %>
  <div data-alert class="flash <%= type %> alert-box radius">
    <p><%= flash[type] %></p>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Rescue Missions</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="/style.css">
  </head>

  <body>
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1>
            <%= link_to "Rescue Missions", root_path %>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <% if !user_signed_in?%>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign in with Github", user_omniauth_authorize_path(:github) %></li>
          <% else %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% end %>
          <li class="divider"></li>
        </ul>
      </section>
    </nav>


    <div class="row">
      <div class="columns 12">

        <%= render 'layouts/flash' %>
        <%= yield %>
        <%= javascript_include_tag "application" %>
      </div>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>

  <%= f.label :title, "Title:" %>
  <%= f.text_field :title %>
  <%= f.label :description, "Description:" %>
  <%= f.text_area :description %>
  <%= f.submit :class => "button" %>
<% end %>

app/views/questions/edit.html.erb
<h3>Editing Question</h3>

<%= render 'form' %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<a href="<%= new_question_path %>" class="button right">Create New Question</a>

<ul>
  <% @questions.each do |question| %>
  <li><a href="<%= question_path(question.id) %>"><%= question.title %></a></li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<h3>Submit a New Question</h3>



<%= render 'form' %>

app/views/questions/show.html.erb
<div class="row">
  <div class="columns large-9">
    <h3><%= @question.title %></h3>
  </div>

  <div class="columns large-3">
    <%= form_tag(question_path(@question.id), method: "delete") do %>
      <ul class="change-links right">
        <li><a href="<%= question_path(@question.id) %>/edit">Edit</a></li>
        <li>
          <%= submit_tag("Delete") %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

<p><%= @question.description %></p>

<a href="<%= questions_path %>" class="right">Back to Questions</a>
<hr />

<h4>Answers</h4>

<ul class="answers">
  <% @question.answers.each do |answer| %>
    <li class="answer"><%= answer.description %></li>
  <% end %>
</ul>

<%= render 'answers/answer_form' %>